export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';

export const CERRAR_SESION = 'CERRAR_SESION';

export const CARGADO = 'CARGADO';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';

export const SUBIR_ARCHIVO = 'SUBIR_ARCHIVO';
export const SUBIR_ARCHIVO_EXITO = 'SUBIR_ARCHIVO_EXITO';
export const SUBIR_ARCHIVO_ERROR = 'SUBIR_ARCHIVO_ERROR';

export const CREAR_ENLACE_EXITO = 'CREAR_ENLACE_EXITO';
export const CREAR_ENLACE_ERROR = 'CREAR_ENLACE_ERROR';

export const LIMPIAR_STATE = 'LIMPIAR_STATE';

export const AGREGAR_PASSWORD = 'AGREGAR_PASSWORD';

export const AGREGAR_DESCARGAS = 'AGREGAR_DESCARGAS';

export const ARCHIVOS = 'ARCHIVOS';

export const HISTORIAL_USUARIO = 'HISTORIAL_USUARIO';
export const HISTORIAL_USUARIO_EXITO = 'HISTORIAL_USUARIO_EXITO';

export const MODAL_CHANGE_EDITAR = 'MODAL_CHANGE_EDITAR';
export const MODAL_CHANGE_DETALLES = 'MODAL_CHANGE_DETALLES';
export const MODAL_CHANGE_ELIMINAR = 'MODAL_CHANGE_ELIMINAR';
export const MODAL_CHANGE_CONTACTO = 'MODAL_CHANGE_CONTACTO';
export const MODAL_CHANGE_COPIAR = 'MODAL_CHANGE_COPIAR';

export const SET_ID_ARCHIVO = 'SET_ID_ARCHIVO';

export const HISTORIAL_ARCHIVO = 'HISTORIAL_ARCHIVO';

export const ENLACE = 'ENLACE';

export const EDITAR_ENLACE = 'EDITAR_ENLACE';
export const EDITAR_ENLACE_EXITO = 'EDITAR_ENLACE_EXITO';
export const EDITAR_ENLACE_ERROR = 'EDITAR_ENLACE_ERROR';

export const CURRENT_PAGE = 'CURRENT_PAGE';

export const EDITAR_FILTRO = 'EDITAR_FILTRO';
export const ACTUALIZAR_HISTORIAL = 'ACTUALIZAR_HISTORIAL';

export const RECUPERAR_CONTRASEÑA_EXITOSO = 'RECUPERAR_CONTRASEÑA_EXITOSO';
export const RECUPERAR_CONTRASEÑA_ERROR = 'RECUPERAR_CONTRASEÑA_ERROR';
export const CAMBIAR_CONTRASEÑA_EXITOSO = 'CAMBIAR_CONTRASEÑA_EXITOSO';
export const CAMBIAR_CONTRASEÑA_ERROR = 'CAMBIAR_CONTRASEÑA_ERROR';

